version: '3'

tasks:
  build:
    cmds:
      - |
        go mod tidy
        go build \
        -ldflags "-X 'github.com/SymmetricalAI/symctl/cmd.version=0.0.1-test'" \
        -o output/symctl main.go
  run:
    cmds:
      - task: build
      - ./output/symctl foo bar --baz
  clean-plugins:
    cmds:
      - rm -rf ~/.symctl-tests
  clean:
    cmds:
      - task: clean-plugins
      - rm -rf output
      - go clean
  prepare-test-directory:
    cmds:
      - mkdir -p ~/.symctl-tests/bin
  prepare-test-plugin:
    cmds:
      - task: prepare-test-directory
      - |
        cat > ~/.symctl-tests/bin/symctl-foo <<EOF
        #!/bin/bash
        echo "Hello, world from foo plugin!"
        echo "Args: \$@"
        echo "One!"
        sleep 1
        echo "Two!"
        echo "Done!"
        EOF
        chmod +x ~/.symctl-tests/bin/symctl-foo
    silent: false
  test-run:
    cmds:
    - task: build
    - task: prepare-test-plugin
    - cp ./output/symctl ~/.symctl-tests/bin/symctl
    - ls -la ~/.symctl-tests/bin
    - export PATH=~/.symctl-tests/bin:$PATH && symctl-foo bar --baz
    - export PATH=~/.symctl-tests/bin:$PATH && symctl --version
    - export PATH=~/.symctl-tests/bin:$PATH && symctl --help
    - export PATH=~/.symctl-tests/bin:$PATH && symctl install https://lalala.com/symctl-foo --version 1.0.0 || true
    - export PATH=~/.symctl-tests/bin:$PATH && symctl install https://lalala.com/symctl-foo || true
    - export PATH=~/.symctl-tests/bin:$PATH && symctl -t install not-url || true
    - export PATH=~/.symctl-tests/bin:$PATH && symctl -t install || true
    - export PATH=~/.symctl-tests/bin:$PATH && symctl -t foo bar --baz
  test-install:
    cmds:
      - task: build
      - task: clean-plugins
      - task: prepare-test-directory
      - cp ./output/symctl ~/.symctl-tests/bin/symctl
      - chmod +x ~/.symctl-tests/bin/symctl
      - export PATH=~/.symctl-tests/bin:$PATH && symctl -t install https://raw.githubusercontent.com/SymmetricalAI/symctl-hello-sh/main/manifest.json
      - export PATH=~/.symctl-tests/bin:$PATH && symctl --help
      - export PATH=~/.symctl-tests/bin:$PATH && symctl -t hello-sh test
  test-upgrade:
    cmds:
      - task: build
      - task: clean-plugins
      - task: prepare-test-directory
      - cp ./output/symctl ~/.symctl-tests/bin/symctl
      - chmod +x ~/.symctl-tests/bin/symctl
      - export PATH=~/.symctl-tests/bin:$PATH && symctl --version
      - export PATH=~/.symctl-tests/bin:$PATH && symctl -t upgrade --dry-run
      - export PATH=~/.symctl-tests/bin:$PATH && symctl -t upgrade
      - export PATH=~/.symctl-tests/bin:$PATH && symctl --version || true
      - export PATH=~/.symctl-tests/bin:$PATH && symctl version || true
