version: '3'

tasks:
  build:
    cmds:
      - |
        go build \
        -ldflags "-X 'main.version=9.9.9-test'" \
        -o output/symctl main.go
  run:
    cmds:
      - task: build
      - ./output/symctl foo bar --baz
  clean-plugins:
    cmds:
      - rm -rf ~/.symctl-tests
  clean:
    cmds:
      - task: clean-plugins
      - rm -rf output
      - go clean
  prepare-test-directory:
    cmds:
      - mkdir -p ~/.symctl-tests/bin
  prepare-test-plugin:
    cmds:
      - task: prepare-test-directory
      - |
        cat > ~/.symctl-tests/bin/symctl-foo <<EOF
        #!/bin/bash
        echo "Hello, world from foo plugin!"
        echo "Args: \$@"
        echo "One!"
        sleep 1
        echo "Two!"
        echo "Done!"
        EOF
        chmod +x ~/.symctl-tests/bin/symctl-foo
    silent: false
  test-run:
    cmds:
    - task: build
    - task: prepare-test-plugin
    - cp ./output/symctl ~/.symctl-tests/bin/symctl
    - export PATH=~/.symctl-tests/bin:$PATH && symctl-foo bar --baz
    - export PATH=~/.symctl-tests/bin:$PATH && symctl version
    - export PATH=~/.symctl-tests/bin:$PATH && symctl install https://lalala.com/symctl-foo --version 1.0.0 || true
    - export PATH=~/.symctl-tests/bin:$PATH && symctl install https://lalala.com/symctl-foo || true
    - export PATH=~/.symctl-tests/bin:$PATH && export DEBUG=1 && symctl install || true
    - export PATH=~/.symctl-tests/bin:$PATH && symctl foo bar --baz
  test-install:
    cmds:
      - task: build
      - task: clean-plugins
      - task: prepare-test-directory
      - cp ./output/symctl ~/.symctl-tests/bin/symctl
      - chmod +x ~/.symctl-tests/bin/symctl
      - export PATH=~/.symctl-tests/bin:$PATH && symctl install https://raw.githubusercontent.com/SymmetricalAI/symctl-hello-sh/main/manifest.json
      - export PATH=~/.symctl-tests/bin:$PATH && symctl hello-sh test
