name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        go-version: [ '1.21.5', '1.22.0' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false # Disable cache because we do not have go.sum so far
      - name: Run tests
        run: go test -v ./... -json > TestResults-${{ matrix.os }}-${{ matrix.go-version }}.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: tests-results-${{ matrix.os }}-${{ matrix.go-version }}
          path: TestResults-${{ matrix.os }}-${{ matrix.go-version }}.json
